import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { delimiter, dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { LaunchProfile } from "./launch-profile.js";
import {
  PROTOCOL_OPERATIONS,
  type HarnessLaunchAdapter,
  type ProtocolOperation,
  type StartupProof,
} from "./harness-adapter.js";

export const OPENCODE_PROVIDER = "openai-codex";
/** OpenCode routes the Codex subscription models under its `openai` provider. */
const OPENCODE_MODEL_PREFIX = "openai";

export type OpencodeAdapterPaths = {
  /** Directory for generated plugin files (the manifest scratch directory). */
  scratchDirectory: string;
};

function opencodeBinaryAvailable(): boolean {
  for (const entry of (process.env.PATH ?? "").split(delimiter)) {
    if (entry && existsSync(join(resolve(entry), "opencode"))) return true;
  }
  return false;
}

function filterProtocolOperations(operations: unknown): ProtocolOperation[] {
  const known = new Set<string>(Object.values(PROTOCOL_OPERATIONS));
  if (!Array.isArray(operations)) return [];
  return operations.filter(
    (operation): operation is ProtocolOperation =>
      typeof operation === "string" && known.has(operation),
  );
}

/** Generated OpenCode plugin source. Attests the lane's session identity into
 * the startup intent file on the first session event. Written defensively:
 * event names are probed, and any mismatch leaves no attestation, which fails
 * dispatch closed rather than launching unproven. */
function pluginSource(mergeImportPath: string): string {
  return `// Generated by the herdr-orchestrator opencode launch adapter.
// Plugin shape per @opencode-ai/plugin: async (ctx) => hooks object, where
// the single event hook receives every event.
import { readFile } from "node:fs/promises";

export const HerdrAttest = async () => {
  const attested = new Set();
  return {
    event: async ({ event }) => {
      const intentPath = process.env.BAA_STARTUP_INTENT;
      if (!intentPath) return;
      const type = event?.type ?? "";
      if (type !== "session.updated" && type !== "session.initialized") return;
      const sessionId =
        event.properties?.sessionID ?? event.properties?.sessionId;
      if (typeof sessionId !== "string" || !sessionId || attested.has(sessionId))
        return;
      attested.add(sessionId);
      let intent;
      try {
        intent = JSON.parse(await readFile(intentPath, "utf8"));
      } catch {
        return;
      }
      if (
        process.env.HERDR_PANE_ID !== intent.paneId ||
        process.env.HERDR_WORKSPACE_ID !== intent.workspaceId
      )
        return;
      const { mergeAttestation } = await import(${JSON.stringify(mergeImportPath)});
      await mergeAttestation(intentPath, {
        version: 1,
        harness: "opencode",
        nonce: intent.nonce,
        paneId: intent.paneId,
        workspaceId: intent.workspaceId,
        source: intent.source,
        profile: intent.profile,
        sessionId,
      });
    },
  };
};
`;
}

/** OpenCode lanes run Luna on the openai-codex subscription via OpenCode's
 * `openai` provider (oauth). Model/effort/MCP/plugin wiring comes from a
 * generated project config; the plugin attests session identity and the MCP
 * bridge merges live protocol operations. */
export function opencodeLaunchAdapter(
  paths: OpencodeAdapterPaths,
): HarnessLaunchAdapter {
  return {
    version: 1,
    kind: "opencode",
    capabilities: {
      startupAttestation: true,
      supportsSessionPersistence: true,
      supportsNativeSessionIdentity: true,
      // OpenCode's adapter only receives launch/config paths; its model list
      // is not an authoritative live provider catalog at this boundary.
      supportsLiveCapabilityDiscovery: false,
      supportsStartupHandshake: true,
    },
    lifecycle: "screen",
    // OpenCode creates its native session lazily, so the dispatcher must
    // submit the first turn that causes the attest plugin and MCP bridge to
    // initialize. Keep this exact text stable: it is deliberately not an
    // assignment or a harness-specific wrapper. Live catalog discovery is
    // explicitly unsupported because no authoritative API is exposed here.
    startupHandshake: "Reply with exactly: READY",
    attestationComplete: (attestation: unknown): boolean => {
      const hello = attestation as {
        sessionId?: unknown;
        operations?: unknown;
      };
      return (
        typeof hello?.sessionId === "string" && Array.isArray(hello?.operations)
      );
    },
    preflight(profile: LaunchProfile): void {
      if (profile.provider !== OPENCODE_PROVIDER)
        throw new Error(
          "Only the openai-codex subscription launch adapter is qualified in this prerequisite.",
        );
      if (!profile.model)
        throw new Error("Exact model id is required; no alias substitution.");
      if (!opencodeBinaryAvailable())
        throw new Error(
          "opencode CLI not found on PATH; install and authenticate before dispatch.",
        );
      // Subscription auth is proven by runtime attestation: an expired
      // credential fails every turn, so no attestation ever appears and
      // dispatch fails closed rather than billing another route.
    },
    launchArguments(
      profile: LaunchProfile,
      source: string,
      context?: { startupIntentPath?: string },
    ): string[] {
      if (!context?.startupIntentPath)
        throw new Error("OpenCode launch requires the startup intent path.");
      const repoRoot = resolve(dirname(source), "..", "..");
      const toolsDirectory = dirname(fileURLToPath(import.meta.url));
      mkdirSync(paths.scratchDirectory, { recursive: true, mode: 0o700 });
      const pluginPath = join(
        paths.scratchDirectory,
        "opencode-attest-plugin.ts",
      );
      writeFileSync(
        pluginPath,
        pluginSource(
          relative(
            paths.scratchDirectory,
            join(toolsDirectory, "attest-merge.mjs"),
          ),
        ),
        { mode: 0o600 },
      );
      const config = {
        model: `${OPENCODE_MODEL_PREFIX}/${profile.model}`,
        plugin: [pluginPath],
        mcp: {
          "herdr-orchestrator": {
            type: "local",
            command: ["node", join(toolsDirectory, "mcp-server.mjs")],
          },
        },
        agent: {
          build: {
            model: `${OPENCODE_MODEL_PREFIX}/${profile.model}`,
            options: { reasoningEffort: profile.thinking },
          },
        },
        permission: {
          edit: "allow",
          bash: {
            "git push": "deny",
            "git merge": "deny",
            "gh pr create": "deny",
            "*": "allow",
          },
          webfetch: "allow",
        },
      };
      writeFileSync(
        join(repoRoot, "opencode.json"),
        JSON.stringify(config, null, 2) + "\n",
        {
          mode: 0o600,
        },
      );
      return ["--model", `${OPENCODE_MODEL_PREFIX}/${profile.model}`];
    },
    verifyStartup(nativeAgent: unknown, attestation: unknown): StartupProof {
      const agent = nativeAgent as {
        agent?: string;
        pane_id?: string;
        workspace_id?: string;
        agent_session?: { kind?: string; value?: string };
      };
      const hello = attestation as {
        paneId?: string;
        workspaceId?: string;
        nonce?: string;
        source?: string;
        profile?: LaunchProfile;
        operations?: unknown;
        sessionId?: string;
      };
      if (!agent || !hello || agent.agent !== "opencode")
        throw new Error("OpenCode native identity mismatch; no work assigned.");
      const kind = agent.agent_session?.kind;
      const value = agent.agent_session?.value;
      if (kind !== "path" && kind !== "id")
        throw new Error(
          "OpenCode native session reference missing; no work assigned.",
        );
      if (typeof value !== "string" || !value)
        throw new Error(
          "OpenCode native session reference missing; no work assigned.",
        );
      if (typeof hello.sessionId !== "string" || !hello.sessionId)
        throw new Error(
          "OpenCode attestation lacks session identity; no work assigned.",
        );
      const attested =
        kind === "id"
          ? value === hello.sessionId
          : value.includes(hello.sessionId);
      if (!attested)
        throw new Error(
          "OpenCode session attestation does not match native identity; no work assigned.",
        );
      if (
        agent.pane_id !== hello.paneId ||
        agent.workspace_id !== hello.workspaceId
      )
        throw new Error("OpenCode startup binding mismatch; no work assigned.");
      return {
        paneId: hello.paneId!,
        workspaceId: hello.workspaceId!,
        nonce: hello.nonce!,
        source: hello.source!,
        profile: hello.profile!,
        operations: filterProtocolOperations(hello.operations),
        session: { kind, value },
      };
    },
  };
}
